# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read  # This grants read access to the contents of the repository

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078The issue in the workflow lies in the `Run linter` step at line 39, where the command `deno lint --rules=all` is used. The error message indicates that the `--rules` flag does not accept the value `all`.

### Solution
To fix the issue, you should remove the `202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x  # Using the latest version of Deno

      - name: Run linter
        run--rules=all` flag or replace it with a valid option.: deno lint # Removed the invalid `--rules=all` According to the [Deno documentation](https://deno argument

      - name: Run tests
        run: deno.land/manual/tools/linter), `deno lint` can be run without the `--rules` flag to apply all available lint test --allow-env --allow-read --allow-write --unstable-kv #ing rules by default.

#### Updated Workflow
Here is Provide permissions for tests to run correctly
`` the corrected workflow file:

```yaml
- name: Run`

### Key Changes
1. **Removed `--rules=all`:** The linter
  run: deno lint # Removed the invalid `--rules `deno lint` command no longer includes the invalid `=all` flag
